nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE','OPTIONS']
        expose_headers: ['*']
        max_age: 9000
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE','OPTIONS']
            max_age: 9000
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['Content-Type']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE','OPTIONS']
            max_age: 9000
            hosts: ['^api\.']