App\Form\Model\PositionDto:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 5
                max: 100
                minMessage: 'The name must be at least {{ limit }} characters long'
                maxMessage: 'The name cannot be longer than {{ limit }} characters'
                allowEmptyString: false
        position:
            - NotBlank: ~
            - Length:
                min: 5
                max: 20
                minMessage: 'The name must be at least {{ limit }} characters long'
                maxMessage: 'The name cannot be longer than {{ limit }} characters'
                allowEmptyString: false
        team_id:
            - NotBlank: ~